version: "3.9"

services:
  web:
    build: .
    container_name: django_ipcam_web
    command: gunicorn ipcam_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./static:/app/static
      - static_volume:/app/staticfiles
      - ./templates:/app/templates
    devices:
      - /dev/video0:/dev/video0
    privileged: true
    depends_on:
      - migrate

  migrate:
    build: .
    command: python manage.py migrate
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  static_volume:
