version: "3.9"

services:
  web:
    build: .
    container_name: django_ipcam_web
    command: gunicorn ipcam_project.wsgi:application --bind 0.0.0.0:8000 --worker-class=gevent --timeout 120
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./static:/app/static
      - static_volume:/app/staticfiles
      - ./templates:/app/templates
      - /usr/local/bin/reboot-host.sh:/usr/local/bin/reboot-host.sh:ro
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/video13:/dev/video13
      - /dev/video14:/dev/video14
      - /dev/video15:/dev/video15
      - /dev/video16:/dev/video16
      - /dev/video18:/dev/video18
      - /dev/video19:/dev/video19
      - /dev/video20:/dev/video20
      - /dev/video21:/dev/video21
      - /dev/video22:/dev/video22
      - /dev/video23:/dev/video23
      - /dev/video31:/dev/video31
    privileged: true
    depends_on:
      - migrate

  migrate:
    build: .
    command: python manage.py migrate
    env_file:
      - .env
    volumes:
      - .:/app

  services:
    django_ipcam_web:
      volumes:
        - /usr/local/bin/reboot-host.sh:/usr/local/bin/reboot-host.sh:ro

volumes:
  static_volume:
