version: "3.9"

services:

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - django
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email dein.email@example.com
      --agree-tos
      --no-eff-email
      -d dein.domain.de"

  django:
    build: .
    container_name: django_ipcam_web
    command: gunicorn ipcam_project.wsgi:application --bind 0.0.0.0:8000 --worker-class=gevent --timeout 120
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./static:/app/static
      - static_volume:/app/staticfiles
      - ./templates:/app/templates
      - ./scripts/reboot-host.sh:/usr/local/bin/reboot-host.sh:ro
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
    privileged: true
    depends_on:
      - migrate
    restart: unless-stopped

  migrate:
    build: .
    command: python manage.py migrate
    env_file:
      - .env
    volumes:
      - .:/app


volumes:
  static_volume:
